package com.cluecompanion.game;
import java.util.*; import org.junit.jupiter.api.Test; import static org.assertj.core.api.Assertions.*;
class GameTest {
 @Test void listsOnlyLobbiesWithRoomToJoin(){GameService service=new GameService();Game open=service.create("Open host");Game started=service.create("Started host");started.addPlayer("Two");started.addPlayer("Three");started.start(started.players().getFirst().id());Game full=service.create("Full host");for(int i=2;i<=6;i++)full.addPlayer("Player "+i);assertThat(service.joinableCodes()).containsExactly(open.code());}
 @Test void onlyHostCanStartWithThreePlayers(){Game g=new Game("ABCDE","Host",new Random(1));UUID host=g.players().getFirst().id();assertThatThrownBy(()->g.start(host)).hasMessageContaining("3");g.addPlayer("Two");g.addPlayer("Three");assertThatThrownBy(()->g.start(g.players().get(1).id())).hasMessageContaining("host");g.start(host);assertThat(g.status()).isEqualTo(Game.Status.PLAYING);assertThat(g.players()).extracting(p->p.hand().size()).containsOnly(6);}
 @Test void capsLobbyAtSix(){Game g=new Game("ABCDE","Host",new Random(1));for(int i=2;i<=6;i++)g.addPlayer("Player "+i);assertThatThrownBy(()->g.addPlayer("Seven")).hasMessageContaining("full");}
 @Test void suggestionMustBeResolvedBeforeTurnDecision(){Game g=started();UUID first=g.currentPlayer().id();assertThatThrownBy(()->g.pass(first)).hasMessageContaining("turn");Game.Suggestion suggestion=suggestionWithMatchFor(g,g.players().get(1));g.enterRoom(first,suggestion.room());g.suggest(first,suggestion);assertThat(g.phase()).isEqualTo(Game.Phase.DISPROVING);assertThat(g.currentResponder()).isEqualTo(g.players().get(1));Card match=g.players().get(1).hand().stream().filter(suggestion.cards()::contains).findFirst().orElseThrow();g.respond(g.players().get(1).id(),match);assertThat(g.phase()).isEqualTo(Game.Phase.DECISION);assertThat(g.eventsFor(first).getLast().privateCard()).isEqualTo(match);g.pass(first);assertThat(g.currentPlayer().id()).isNotEqualTo(first);}
 @Test void suggestionMustUseTheRoomEntered(){Game g=started();UUID first=g.currentPlayer().id();List<Card> rooms=Deck.cards().stream().filter(c->c.type()==Card.Type.ROOM).toList();g.enterRoom(first,rooms.getFirst());Game.Suggestion suggestion=new Game.Suggestion(Deck.cards().stream().filter(c->c.type()==Card.Type.SUSPECT).findFirst().orElseThrow(),Deck.cards().stream().filter(c->c.type()==Card.Type.WEAPON).findFirst().orElseThrow(),rooms.get(1));assertThatThrownBy(()->g.suggest(first,suggestion)).hasMessageContaining("room you entered");}
 @Test void incorrectAccusationEliminatesPlayerAndSkipsTheirLaterTurns(){Game g=started();UUID first=g.currentPlayer().id();Game.Suggestion wrong=wrongAccusation(g);g.noRoom(first);g.accuse(first,wrong);assertThat(g.players().getFirst().eliminated()).isTrue();assertThat(g.eventsFor(first).getLast().message()).contains("incorrectly accused",wrong.suspect().name(),wrong.weapon().name(),wrong.room().name());UUID second=g.currentPlayer().id();g.noRoom(second);g.pass(second);UUID third=g.currentPlayer().id();g.noRoom(third);g.pass(third);assertThat(g.currentPlayer().id()).isEqualTo(second);}
 @Test void correctAccusationFinishesGameAndRevealsSolution(){Game g=started();UUID first=g.currentPlayer().id();List<Card> solution=solutionCards(g);Game.Suggestion accusation=new Game.Suggestion(ofType(solution,Card.Type.SUSPECT),ofType(solution,Card.Type.WEAPON),ofType(solution,Card.Type.ROOM));g.noRoom(first);assertThat(g.accuse(first,accusation)).isTrue();assertThat(g.status()).isEqualTo(Game.Status.FINISHED);assertThat(g.winner()).isEqualTo(first);assertThat(g.solution()).containsExactlyInAnyOrderElementsOf(solution);assertThat(g.eventsFor(first).getLast().message()).contains("correctly accused","game is over");}
 private Game.Suggestion wrongAccusation(Game g){List<Card> solution=solutionCards(g);return new Game.Suggestion(Deck.cards().stream().filter(c->c.type()==Card.Type.SUSPECT&&!solution.contains(c)).findFirst().orElseThrow(),ofType(solution,Card.Type.WEAPON),ofType(solution,Card.Type.ROOM));}
 private List<Card> solutionCards(Game g){List<Card> dealt=g.players().stream().flatMap(p->p.hand().stream()).toList();return Deck.cards().stream().filter(c->!dealt.contains(c)).toList();}
 private Card ofType(List<Card> cards,Card.Type type){return cards.stream().filter(c->c.type()==type).findFirst().orElseThrow();}
 private Game.Suggestion suggestionWithMatchFor(Game g,Game.Player responder){Card held=responder.hand().getFirst();List<Card> solution=solutionCards(g);Card suspect=held.type()==Card.Type.SUSPECT?held:ofType(solution,Card.Type.SUSPECT);Card weapon=held.type()==Card.Type.WEAPON?held:ofType(solution,Card.Type.WEAPON);Card room=held.type()==Card.Type.ROOM?held:ofType(solution,Card.Type.ROOM);return new Game.Suggestion(suspect,weapon,room);}
 private Game started(){Game g=new Game("ABCDE","Host",new Random(2));g.addPlayer("Two");g.addPlayer("Three");g.start(g.players().getFirst().id());return g;}
}
