package com.cluecompanion.game;
import java.util.*; import org.junit.jupiter.api.Test; import static org.assertj.core.api.Assertions.*;
class GameTest {
 @Test void onlyHostCanStartWithThreePlayers(){Game g=new Game("ABCDE","Host",new Random(1));UUID host=g.players().getFirst().id();assertThatThrownBy(()->g.start(host)).hasMessageContaining("3");g.addPlayer("Two");g.addPlayer("Three");assertThatThrownBy(()->g.start(g.players().get(1).id())).hasMessageContaining("host");g.start(host);assertThat(g.status()).isEqualTo(Game.Status.PLAYING);assertThat(g.players()).extracting(p->p.hand().size()).containsOnly(6);}
 @Test void capsLobbyAtSix(){Game g=new Game("ABCDE","Host",new Random(1));for(int i=2;i<=6;i++)g.addPlayer("Player "+i);assertThatThrownBy(()->g.addPlayer("Seven")).hasMessageContaining("full");}
 @Test void passAdvancesTurnDirectlyAfterDeal(){Game g=started();UUID first=g.currentPlayer().id();g.pass(first);assertThat(g.currentPlayer().id()).isNotEqualTo(first);assertThat(g.phase()).isEqualTo(Game.Phase.ACTION);}
 @Test void incorrectAccusationEliminatesPlayerAndSkipsTheirLaterTurns(){Game g=started();UUID first=g.currentPlayer().id();Game.Suggestion wrong=wrongAccusation(g);g.accuse(first,wrong);assertThat(g.players().getFirst().eliminated()).isTrue();assertThat(g.eventsFor(first).getLast().message()).contains("incorrectly accused",wrong.suspect().name(),wrong.weapon().name(),wrong.room().name());UUID second=g.currentPlayer().id();g.pass(second);UUID third=g.currentPlayer().id();g.pass(third);assertThat(g.currentPlayer().id()).isEqualTo(second);}
 @Test void correctAccusationFinishesGameAndRevealsSolution(){Game g=started();UUID first=g.currentPlayer().id();List<Card> solution=solutionCards(g);Game.Suggestion accusation=new Game.Suggestion(ofType(solution,Card.Type.SUSPECT),ofType(solution,Card.Type.WEAPON),ofType(solution,Card.Type.ROOM));assertThat(g.accuse(first,accusation)).isTrue();assertThat(g.status()).isEqualTo(Game.Status.FINISHED);assertThat(g.winner()).isEqualTo(first);assertThat(g.solution()).containsExactlyInAnyOrderElementsOf(solution);assertThat(g.eventsFor(first).getLast().message()).contains("correctly accused","game is over");}
 private Game.Suggestion wrongAccusation(Game g){List<Card> solution=solutionCards(g);return new Game.Suggestion(Deck.cards().stream().filter(c->c.type()==Card.Type.SUSPECT&&!solution.contains(c)).findFirst().orElseThrow(),ofType(solution,Card.Type.WEAPON),ofType(solution,Card.Type.ROOM));}
 private List<Card> solutionCards(Game g){List<Card> dealt=g.players().stream().flatMap(p->p.hand().stream()).toList();return Deck.cards().stream().filter(c->!dealt.contains(c)).toList();}
 private Card ofType(List<Card> cards,Card.Type type){return cards.stream().filter(c->c.type()==type).findFirst().orElseThrow();}
 private Game started(){Game g=new Game("ABCDE","Host",new Random(2));g.addPlayer("Two");g.addPlayer("Three");g.start(g.players().getFirst().id());return g;}
}
